//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> Effort { get; set; }
        public Nullable<int> RemainingWork { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Priorities Priorities { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual States States { get; set; }
    }
}
